#!/usr/bin/env bash

FZF_HOME="${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/fzf"

# More details in .lib/README.md
if [[ ! -x "$FZF_HOME/install" ]]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git "$FZF_HOME"
fi

"$FZF_HOME/install" --xdg --all
