#!/usr/bin/env bash

CURRENT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$CURRENT_DIR/../../.lib/scripts/common.bash"

shallow_clone https://github.com/junegunn/fzf.git "$CACHE_ROOT/fzf"
makelink   "$HOME/.fzf" "$CACHE_ROOT/fzf"
verifylink "$HOME/.fzf" "$CACHE_ROOT/fzf"

~/.fzf/install --all
