#!/usr/bin/env bash

# http://stackoverflow.com/a/6110446
set -e
trap 'prev_cmd=$this_cmd; this_cmd=$BASH_COMMAND' DEBUG
trap 'EC=$?; BAD_CMD="$prev_cmd"; [[ $EC -ne 0 ]] && echo "Exit: $EC, due to: $BAD_CMD"' EXIT

CACHE_ROOT="$HOME/.cache/dotfiles"

[[ ! -d "$CACHE_ROOT"           ]] && mkdir -p "$CACHE_ROOT"
[[ ! -d "$CACHE_ROOT/fzf" ]] && git clone --depth 1 https://github.com/junegunn/fzf.git "$CACHE_ROOT/fzf" || true

[[ ! -e "$HOME/.fzf" ]] && ln -svf "$CACHE_ROOT/fzf" "$HOME/.fzf"

[[ "$(readlink "$HOME/.fzf")" == "$CACHE_ROOT/fzf" ]]

~/.fzf/install --all
