#!/usr/bin/env bash

# More details in .lib/README.md
export PKG_TYPE="brew"
pkg-install tmux
pkg-install byobu

[[ -d ~/.tmux/plugins/tpm/.git ]] || {
  command git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  ~/.tmux/plugins/tpm/bin/install_plugins
}
