#!/usr/bin/env bash

# http://stackoverflow.com/a/6110446
set -e
trap 'prev_cmd=$this_cmd; this_cmd=$BASH_COMMAND' DEBUG
trap 'EC=$?; BAD_CMD="$prev_cmd"; [[ $EC -ne 0 ]] && echo "Exit: $EC, due to: $BAD_CMD"' EXIT

CACHE_ROOT="$HOME/.cache/dotfiles"

[[ ! -d "$CACHE_ROOT/tmux" ]] && mkdir -p "$CACHE_ROOT"

[[ ! -e "$HOME/.tmux" ]] && ln -svf "$CACHE_ROOT/tmux" "$HOME/.tmux"

[[ "$(readlink "$HOME/.tmux")" == "$CACHE_ROOT/tmux" ]]
