#!/usr/bin/env bash

CURRENT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$CURRENT_DIR/../../.lib/scripts/common.bash"

cache_mkdir_p            "tmux"
cache_makelink   ".tmux" "tmux"
cache_verifylink ".tmux" "tmux"
