#!/usr/bin/env bash

CURRENT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$CURRENT_DIR/../../.lib/scripts/common.bash"

mkdir_p "$CACHE_ROOT/tmux"
makelink   "$HOME/.tmux" "$CACHE_ROOT/tmux"
verifylink "$HOME/.tmux" "$CACHE_ROOT/tmux"
