#!/usr/bin/env bash

CURRENT_DIR="$(dirname "${BASH_SOURCE[0]}")"
source "$CURRENT_DIR/../../.lib/scripts/common.bash"

shallow_clone https://github.com/syl20bnr/spacemacs "$CACHE_ROOT/spacemacs"
makelink   "$HOME/.emacs.d" "$CACHE_ROOT/spacemacs"
verifylink "$HOME/.emacs.d" "$CACHE_ROOT/spacemacs"
